spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/booksys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://121.41.91.101:3306/booksys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#    password: Cyt1694458081


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cyt.library.bean
server:
  port: 8084
